#!name=阿里云盘cookie
#!desc=阿里云盘获取cookie
#!homepage=https://github.com/deezertidal
#!author=lowking
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/aliyun.png


#cookie获取成功后请禁用
# 阿里云盘签到cookie=type=http-response,pattern=https:\/\/auth.(aliyundrive|alipan).com\/v2\/account\/token,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/ali/aliYunPanCheckIn.js


[MITM] 
hostname= %APPEND% auth.alipan.com
