#!name=Shadowrocket
#!desc=Shadowrocket配置文件模块
#!homepage=https://github.com/ZZM365-CN/IOS-Rules

[Proxy Group]
# > 策略组
Disney+ = select,PROXY,🇭🇰 香港,🇸🇬 新加坡,🇨🇳 台湾,🇯🇵 日本, select=0
Netflix = select,PROXY,🇭🇰 香港,🇸🇬 新加坡,🇨🇳 台湾,🇯🇵 日本, select=0
哔哩哔哩 = select,DIRECT,PROXY,🇭🇰 香港,🇨🇳 台湾, select=0
新浪微博 = select,DIRECT,PROXY, select=0
微软服务 = select,DIRECT,PROXY, select=0
苹果服务 = select,DIRECT,PROXY, select=0
🇭🇰 香港 = select, update-interval=0, policy-regex-filter=(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|美)).)*$, no-alert=0, hidden=0, include-all-proxies=0
🇸🇬 新加坡 = select, update-interval=0, policy-regex-filter=(?=.*(新|狮|獅|SG|(?i)Singapore))^((?!(港|台|日|韩|兰|美)).)*$, no-alert=0, hidden=0, include-all-proxies=0
🇨🇳 台湾 = select, update-interval=0, policy-regex-filter=(?=.*(台|TW|(?i)Taiwan))^((?!(港|日|韩|新|美)).)*$, no-alert=0, hidden=0, include-all-proxies=0
🇯🇵 日本 = select, update-interval=0, policy-regex-filter=(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$, no-alert=0, hidden=0, include-all-proxies=0
[Rule]
# > 微软服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Microsoft/Microsoft.list,微软服务
# > 苹果服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple.list,苹果服务
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple_Domain.list,苹果服务
# > 社交平台
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Weibo/Weibo.list,新浪微博
# > 流媒体
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Netflix/Netflix.list,NETFLIX
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Disney/Disney.list,DISNEY+
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/BiliBili/BiliBili.list,哔哩哔哩
# > China
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/China/China.list,DIRECT
RULE-SET, https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaIPs/ChinaIPs.list,DIRECT
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/China/China_Domain.list,DIRECT
# > 本地/局域网地址,下载
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Lan/Lan.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Download/Download.list,DIRECT
# > Proxy
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Global/Global.list,PROXY
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Global/Global_Domain.list,PROXY
# > GeoIP China,与ChinaIPs二选一
GEOIP,CN,DIRECT
# > DNS 查询失败走 Final 规则
FINAL,PROXY
