[Rule]
# > Apple API
DOMAIN-KEYWORD,apple.com.akadns.net,DIRECT
DOMAIN-KEYWORD,icloud.com.akadns.net,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,apple.co,DIRECT
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
DOMAIN-SUFFIX,apple-mapkit.com,DIRECT
DOMAIN-SUFFIX,appsto.re,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,icloud-content.com,DIRECT
DOMAIN-SUFFIX,itunes.com,DIRECT
DOMAIN-SUFFIX,me.com,DIRECT
DOMAIN-SUFFIX,mzstatic.com,DIRECT
IP-CIDR,17.0.0.0/8,no-resolve,DIRECT
IP-CIDR,63.92.224.0/19,no-resolve,DIRECT
IP-CIDR,65.199.22.0/23,no-resolve,DIRECT
IP-CIDR,139.178.128.0/18,no-resolve,DIRECT
IP-CIDR,144.178.0.0/19,no-resolve,DIRECT
IP-CIDR,144.178.36.0/22,no-resolve,DIRECT
IP-CIDR,144.178.48.0/20,no-resolve,DIRECT
IP-CIDR,192.35.50.0/24,no-resolve,DIRECT
IP-CIDR,198.183.17.0/24,no-resolve,DIRECT
IP-CIDR,205.180.175.0/24,no-resolve,DIRECT

# > Apple News
DOMAIN-SUFFIX,apple.comscoreresearch.com,DIRECT
DOMAIN-SUFFIX,apple.news,DIRECT

# > Apple Maps
PROCESS-NAME,com.apple.geod,DIRECT

RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Netflix/Netflix.list,NETFLIX
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Disney/Disney.list,DISNEY+
